version: '3'

services:
  postgres:
    image: postgres:16
    container_name: modern-blog-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: modern_blog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
